language: go

go:
  - 1.7.x
  - master

script:
  - go install
  - go test -v github.com/Droi-SDK/droi-checker
  - go test -v github.com/Droi-SDK/droi-checker/commands
  - go test -v github.com/Droi-SDK/droi-checker/logger

