version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.8
    working_directory: /go/src/github.com/Droi-SDK/droi-checker
    steps:
      - checkout
      # to install glide
      - run: curl https://glide.sh/get | sh

      # Cache vendor/
      - restore_cache:
          keys:
            - glide-cache-{{ checksum "glide.lock" }}
            - glide-cache
      - run: glide install
      - save_cache:
          key: glide-cache-{{ checksum "glide.lock" }}
          paths: vendor/

      - run: go test $(glide novendor)